### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/exercise1-R-python-tutorial-vishalbhashyaam#1]
Hi Vishal,

Great work on the assignment. Some minor feedback:

It's important to have authorship on all notebooks (first name, last name)
This changes makes the notebook more readable and shareable.

I am giving you full credit, contingent on you fixing these minor issues by September 15th.
-Greg

**Comment by vishalbhashyaam** [comment]
Already added the author in .qmd
